### ISSUE TITLE
[BUG] Cannot read property 'total_weight' of undefined

### ISSUE THREAD

**Issue by ToadtheFungus** [YannD-Deltagon/BeamNG_eTacho#4]
Getting an issue where the tacho doesn't load in properly

Log below is from starting the game, loading into Small Grid with a modless Piccolina config, then exiting, all after deactivating every mod except this one and cleaning cache

![Screenshot 2023-08-24 014329](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/36657aaf-008b-4554-826c-d37307bdad5f)
[beamng.log](https://github.com/YDeltagon/BeamNG_Tacho3/files/12425771/beamng.log)

**Comment by YannD-Deltagon** [comment]
Hello, thank you for the report, indeed, I also had the problem, I will try to patch it

**Comment by YannD-Deltagon** [comment]
![image](https://github.com/YDeltagon/BeamNG_Tacho3/assets/70691658/baad29b3-5cc7-49bc-b98b-21e140dd8a9e)

Update is push on the REPO
Wait the dev :)

**Comment by YannD-Deltagon** [comment]
It's live
Try it ;)

**Comment by Bogle911** [comment]
Hey buddy, had the same issue too and redownloaded it in the repo, but for some reason they still won't work (with the same errors in the console). Maybe it's a mod I have or something? 
![image](https://github.com/YDeltagon/BeamNG_Tacho3/assets/100134864/82b6ad77-4c1c-460b-a341-2b4e644eb8df)

**Comment by YannD-Deltagon** [comment]
You use a vehicule mod ?
I have 200 mods on a server, with Tacho3, and I don't have the problem :D

**Comment by YannD-Deltagon** [comment]
I would have to manage to reproduce it, how do you do it? what actions?

**Comment by ToadtheFungus** [comment]
![Screenshot 2023-08-25 115234](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/124b4a92-29b9-46eb-867e-29c3eb8e7efc)
launched BeamNG in safe mode(too lazy to reactivate 60/140 of my mods again), pasted the tacho in the mod folder and added it to the ui, getting the same issue as before with the same error message, just this time with 0s instead of NaNs

Edit: Whenever you end up making another fix, can you drop a zip of the mod somewhere here for us to test on our end? Then we don't have to wait a while for it to get approved on the beam repo

**Comment by ToadtheFungus** [comment]
![Screenshot 2023-08-26 003221](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/570344e9-b847-4997-b36f-6b9cd60a5925)
Apparently the tacho started working again after i removed the ui app and added the basic version, then added the v2 tach back in, no idea what was going on beforehand
I guess if this method doesn't end up working for others if they end up getting this issue, then this can be reopened in the future

**Comment by YannD-Deltagon** [comment]
@Bogle911 ?

**Comment by YannD-Deltagon** [comment]
@ToadtheFungus Thank you for the feedback, for the moment, I can't create the error on my side

**Comment by MlordSlav** [comment]
Im having the same issue as @ToadtheFungus where it doesnt work but adding the basic version then removing it suddenly makes it tick, though it isnt persistent a game relaunch means I have to redo that step (sorry if youre already working on a fix im just throwing my hat into the ring)

**Comment by YannD-Deltagon** [comment]
Y'all have NO other mods, and you add my mods by hand?

**Comment by Bogle911** [comment]
> @Bogle911 ?

Sorry for the late reply, but yeah I have a majority of my mods off (including anything that effects the ui except yours). And somehow it's still unable to read it.

**Comment by YannD-Deltagon** [comment]
Are you installing the mods via the repo?
You haven't enhanced tacho yet?

I tested on 3 PCs? made complete reinstalls, I absolutely cannot reproduce the problem

I'm going to try a new ZIP, I'll post it to you here during the day

**Comment by YannD-Deltagon** [comment]
Try : 
[fix4.zip](https://github.com/YDeltagon/BeamNG_Tacho3/files/12495727/fix4.zip)

@Bogle911 @MlordSlav @ToadtheFungus 

**I finally generate the bug, and therefore, correct it**

**Comment by Bogle911** [comment]
![image](https://github.com/YDeltagon/BeamNG_Tacho3/assets/100134864/0034c575-236a-45d6-b0ce-6238534b3263)
Works as it should now, nice job!
