### ISSUE TITLE
No info showing on Tach

### ISSUE THREAD

**Issue by Bingegamer** [YannD-Deltagon/BeamNG_eTacho#7]
I updated the mod and cleared my cache after but the tach still does not show any info about the car or rpm. CTRL+L and CTRL+U do not work either. Any ideas?

![BeamNG drive x64_BRhlAqAfzs](https://github.com/YDeltagon/BeamNG_Tacho3/assets/28022172/72f77597-6b58-4890-a427-e2274d02e06f)

**Comment by YannD-Deltagon** [comment]
Try the new update 2.1 ;)

**Comment by ToadtheFungus** [comment]
If you have v2.1, try removing the app from the ui and adding in the basic variant, hopefully it'll decide to work again

**Comment by Bingegamer** [comment]
> Try the new update 2.1 ;)

I updated to 2.1 and looks like I had nutunabe's enhanced tach still active so I removed it and now it works 😁

**Comment by ToadtheFungus** [comment]
> > Try the new update 2.1 ;)
> 
> I updated to 2.1 and looks like I had nutunabe's enhanced tach still active so I removed it and now it works 😁

for me i'm noticing that every time i start the game i have to add in the basic variant of the tach to get the other tach variants to stop having the "cannot read 'property' of undefined" issue(don't actually have to remove the existing v2 tach)

Maybe the basic variant has code that works perfectly and the others still have the issue?

![Screenshot 2023-08-26 072821](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/4c0d3488-01cf-4b08-be1d-fa376b0e1e0f)
![Screenshot 2023-08-26 073018](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/2cc90e95-ddeb-4614-9701-2f851d0575d8)

**Comment by YannD-Deltagon** [comment]
Ok, delete the mods, and try this : 
[ui.zip](https://github.com/YDeltagon/BeamNG_Tacho3/files/12445362/ui.zip)

**Comment by ToadtheFungus** [comment]
> Ok, delete the mods, and try this : [ui.zip](https://github.com/YDeltagon/BeamNG_Tacho3/files/12445362/ui.zip)

![Screenshot 2023-08-26 103535](https://github.com/YDeltagon/BeamNG_Tacho3/assets/91818672/36653260-b8e8-46f7-ba45-0f2b9335de72)
[beamng.log](https://github.com/YDeltagon/BeamNG_Tacho3/files/12445565/beamng.log)
tried in safe mode

50.62758|E|CEF.MainGEUI#local://local/ui/common/EnhancedTacho/controllers.js:230| Uncaught SyntaxError: Unexpected token .
 50.67219|E|CEF.MainGEUI#local://local/ui/modules/apps/enhancedTacho3V2/svg-script.js:68| Uncaught ReferenceError: TachometerV2Controller is not defined
 50.67229|E|CEF.MainGEUI#local://local/ui/modules/apps/enhancedTacho3V2/app.js:56| Uncaught TypeError: svg.wireThroughUnitSystem is not a function
 50.68981|E|CEF.MainGEUI#local://local/ui/lib/ext/angular/angular.js:13920| TypeError: svg.update is not a function
    at scope.$on (local://local/ui/modules/apps/enhancedTacho3V2/app.js:62:17)
    at Scope.$broadcast (local://local/ui/lib/ext/angular/angular.js:18005:28)
    at streamUpdateHandler (local://local/ui/ui-vue/dist/index.js:48:6164)
    at n.length.n.forEach.r (local://local/ui/ui-vue/dist/index.js:48:6959)
    at Array.forEach (<anonymous>)
    at _runHandlers (local://local/ui/ui-vue/dist/index.js:48:6948)
    at window.streamUpdate.e (local://local/ui/ui-vue/dist/index.js:48:5731)
    at <anonymous>:1:37

**Comment by YannD-Deltagon** [comment]
Hmmm
Well, I'll do some tests tomorrow, but since I can't reproduce the error, it's a bit hot
You add the mod by hand in zip?

**Comment by ToadtheFungus** [comment]
> Hmmm Well, I'll do some tests tomorrow, but since I can't reproduce the error, it's a bit hot You add the mod by hand in zip?

I launched BeamNG in safe mode, copied the zip into the temp mod folder, and added it to the ui
The exact same issue also happened when loading the game normally

**Comment by thegamerpt13** [comment]
I left a review on the repo explaining what might be causing the problem of every tacho reading zero, I was having the same problem and fixed it by deactivating the simple power weight ratio mod (if you have the old enhanced tacho, it will probably create the same issue, so you should disable it too). So yeah, the reason why this is happening is because of the two mods that are now integrated

**Comment by YannD-Deltagon** [comment]
Duplicated #4
